[package]
name = "rn-inspector-mirror"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
base64 = "0.22.1"
anyhow = "1.0.86"

[[bin]]
name = "mirror"
path = "src/main.rs"
